In [1]:
import numpy as np
import torch

In [ ]:
SEED = 1234

In [ ]:
np.random.seed(SEED)
torch.manual_seed(SEED)

## Basics

In [2]:
x = torch.randn(2, 3)
print(f"Type: {x.type()}")
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Type: torch.FloatTensor
Size: torch.Size([2, 3])
Values: 
tensor([[ 1.1346,  0.4961, -2.1610],
        [-0.6730, -1.4208,  1.9304]])


In [3]:
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [5]:
x = torch.Tensor([[1, 2, 3],[4, 5, 6]])
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [6]:
# NumPy array → Tensor
x = torch.Tensor(np.random.rand(2, 3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.2251, 0.7589, 0.6443],
        [0.7507, 0.6917, 0.2180]])


In [8]:
# Changing tensor type
x = torch.Tensor(3, 4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Values: 
tensor([[1.3419e-35, 0.0000e+00, 1.3394e-35, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]])
Type: torch.LongTensor


## Operations

In [9]:
# Addition
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = x + y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([2, 3])
Values: 
tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [11]:
# Dot product
x = torch.ones(2, 3)
y = torch.ones(3, 2)
z = torch.mm(x, y)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([2, 2])
Values: 
tensor([[3., 3.],
        [3., 3.]])


In [12]:
# Transpose
x = torch.randn(2, 3)
print(f"Size: {x.shape}")
print(f"Values: \n{x}")
y = torch.t(x)
print(f"Size: {y.shape}")
print(f"Values: \n{y}")

Size: torch.Size([2, 3])
Values: 
tensor([[ 0.4613, -0.0200,  0.6089],
        [ 0.3529,  0.5521, -0.9392]])
Size: torch.Size([3, 2])
Values: 
tensor([[ 0.4613,  0.3529],
        [-0.0200,  0.5521],
        [ 0.6089, -0.9392]])


In [13]:
# Reshape
x = torch.randn(2, 3)
z = x.view(3, 2)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.5814, -2.7788],
        [-0.2536,  0.7825],
        [-0.5233,  0.8383]])


In [16]:
# Dangers of reshaping (unintended consequences)
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])



In [17]:
a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])



In [18]:
b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])



In [ ]:

c = b.view(b.size(0), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")

In [15]:
# Dimensional operations
x = torch.randn(2, 3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0) # add each row's value for every column
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[-0.1724,  0.5296, -0.5706],
        [ 1.8203, -0.1995,  0.1099]])
Values: 
tensor([ 1.6479,  0.3302, -0.4607])
Values: 
tensor([-0.2134,  1.7307])
